name: cardio
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.3.1
  - torchvision
  - cudatoolkit=10.1
  - matplotlib
  - xlrd=1.2.0
  # - tensorflow
  - pillow=8.1.2
  - tqdm
  - imageio
  - jupyterlab
    # - simpleitk
  - openpyxl=3.0.9
  - pip:
    - simpleitk==2.1.0
    - terminaltables
    - easydict
    - albumentations
    - pydicom==1.3.0
    - pandas
    - shapely==1.8.0
    - loguru==0.5.3
    - pykalman==0.9.5
    - opencv-contrib-python==4.4.0.46

      # prefix: D:\VishC\echo\envs\cardio
